name: Preview Publish

on:
  issue_comment:
    types: [created]

jobs:
  detect-command:
    # PR上のコメントであり、"/prev "から始まる内容であれば実行する
    if: github.event_name == 'issue_comment' && contains(github.event.comment.html_url, '/pull/') && startsWith(github.event.comment.body, '/prev ')
    permissions:
      contents: "read"
    runs-on: ubuntu-latest
    timeout-minutes: 30
    outputs:
      app: ${{ steps.detect_app.outputs.app }}
      branch: ${{ steps.detect_pr.outputs.branch }}
      base_branch: ${{ steps.detect_pr.outputs.base_branch }}
      sha: ${{ steps.detect_pr.outputs.sha }}
      pr_number: ${{ steps.detect_pr.outputs.pr_number }}
      env: ${{ steps.detect_env.outputs.env || steps.detect_pr.outputs.base_branch }}
    steps:
      - name: Detect application name
        id: detect_app
        run: |
          app_name=$(echo "${{ github.event.comment.body }}" | sed 's|^/prev ||')

          valid_app_names=(foo bar buz)
          for valid_app_name in "${valid_app_names[@]}"; do
            if [[ $app_name == $valid_app_name ]]; then
              echo "Valid app name: $app_name"
              echo "app=$app_name" >> $GITHUB_OUTPUT
              exit 0
            fi
          done

          echo "Invalid app name: $app_name"
          exit 1

      - name: Detect PR
        id: detect_pr
        run: |
          PR=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" ${{ github.event.issue.pull_request.url }})
          echo "branch=$(echo $PR | jq -r '.head.ref')" >> $GITHUB_OUTPUT
          echo "base_branch=$(echo $PR | jq -r '.base.ref')" >> $GITHUB_OUTPUT
          echo "sha=$(echo $PR | jq -r '.head.sha')" >> $GITHUB_OUTPUT
          echo "pr_number=$(echo $PR | jq -r '.number')" >> $GITHUB_OUTPUT

      - name: Check env option
        id: detect_env
        if: contains(github.event.comment.body, '--env ')
        run: |
          env_name=$(echo $input | sed -n 's/.*--env \([^ ]*\).*/\1/p')

          valid_env_names=(stg qa dev)
          for valid_env_name in "${valid_env_names[@]}"; do
            if [[ $env_name == $valid_env_name ]]; then
              echo "Valid env name: $env_name"
              echo "env=$env_name" >> $GITHUB_OUTPUT
              exit 0
            fi
          done

          echo "Invalid env option: $env_name"
          exit 1

      - name: Check if base branch is env branch
        run: |
          base_branch=${{ steps.detect_pr.outputs.base_branch }}

          valid_base_branches=(stg qa dev)
          for valid_base_branch in "${valid_base_branches[@]}"; do
            if [[ $base_branch == $valid_base_branch ]]; then
              echo "Valid base branch: $valid_base_branch"
              exit 0
            fi
          done

          echo "Invalid base branch: $base_branch"
          exit 1

  publish-preview:
    needs: detect-command
    permissions:
      id-token: "write"
      issues: "write"
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Dump vars
        run: |
          echo "app=${{ needs.detect-command.outputs.app }}"
          echo "branch=${{ needs.detect-command.outputs.branch }}"
          echo "sha=${{ needs.detect-command.outputs.sha }}"
          echo "pr_number=${{ needs.detect-command.outputs.pr_number }}"
          echo "env=${{ needs.detect-command.outputs.env }}"
